layout: {zmk_keyboard: lintilla}
layers:
  Colemak DH:
  - - '&lp_mc'
    - {t: DEL, h: keyboard}
    - {t: ESCAPE, h: LGUI, s: '`'}
    - Q
    - W
    - F
    - P
    - B
    - J
    - L
  - - U
    - Y
    - ;
    - '|'
    - TAB
    - {t: A, h: LGUI}
    - {t: R, h: LALT}
    - {t: S, h: LSHFT}
    - {t: T, h: LCTRL}
    - G
  - - M
    - {t: N, h: RCTRL}
    - {t: E, h: RSHFT}
    - {t: I, h: RALT}
    - {t: O, h: RGUI}
    - {t: RSHFT, h: sticky, s: '&caps_word'}
    - Z
    - X
    - C
    - D
  - - V
    - K
    - H
    - {t: ',', s: .}
    - '-'
    - /
    - {t: SPACE, h: numpad}
    - {t: SPACE, h: symbols}
    - RETURN
    - {t: BSPC, s: DEL}
  - - {t: SPACE, h: navigation}
    - '&magic_shift LSHFT 0'
  QWERTY:
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - E
    - R
    - T
    - Y
    - U
  - - I
    - O
    - P
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - A
    - S
    - D
    - F
    - {t: ▽, type: trans}
  - - H
    - J
    - K
    - L
    - ;
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - C
    - V
  - - B
    - N
    - M
    - ','
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  numpad:
  - ['', '', '', Ctl+Q, Ctl+W, Ctl+F, Ctl+P, '', /, '7']
  - ['8', '9', '-', BSPC, GLOBE, Ctl+A, Ctl+R, Ctl+S, Ctl+T, LSHFT]
  - ['*', '4', '5', '6', +, RET, Ctl+Z, Ctl+X, Ctl+C, Ctl+D]
  - - Ctl+V
    - ':'
    - '1'
    - '2'
    - '3'
    - '='
    - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - ','
  - [SPC, '0']
  navigation:
  - ['', '', '', Ctl+Q, Ctl+W, Ctl+F, Ctl+P, '', PG UP, '']
  - [DEL, '', '', '', GLOBE, Ctl+A, Ctl+R, Ctl+S, Ctl+T, LSHFT]
  - [HOME, LEFT, UP, RIGHT, END, '', Ctl+Z, Ctl+X, Ctl+C, Ctl+D]
  - - Ctl+V
    - PG DN
    - ''
    - DOWN
    - ''
    - ''
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {type: held}
    - {t: ▽, type: trans}
  symbols:
  - ['', '', <, '!', '@', '#', $, '%', ^, '&']
  - ['*', '{', '}', '>', '''', '1', '2', '3', '4', '5']
  - ['6', '7', '8', '9', '0', '"', '[', '{', _, '-']
  - - ','
    - .
    - +
    - '='
    - '}'
    - ']'
    - {t: ▽, type: trans}
    - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  function:
  - ['', '', '', '', '', '', '', '', '', F7]
  - [F8, F9, '', '', GLOBE, LALT, LGUI, LSHFT, LCTL, RALT]
  - ['', F4, F5, F6, '', '', '', '', '', '']
  - - ''
    - ''
    - F1
    - F2
    - F3
    - ''
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - ''
    - F12
  - [F11, F10]
  keyboard:
  - - '&flash 6'
    - {type: held}
    - BRI UP
    - ''
    - ''
    - Gui+Sft+4
    - Gui+Ctl+Sft+4
    - VOL UP
    - '&ind_con'
    - ''
  - - '&ind_bat'
    - ''
    - ''
    - ''
    - BRI DN
    - {t: '&bt_sel', h: '&bt_clr'}
    - {t: '&bt_sel 1', h: '&bt_clr 1'}
    - {t: '&bt_sel 2', h: '&bt_clr 2'}
    - {t: '&bt_sel 3', h: '&bt_clr 3'}
    - {t: '&bt_sel 4', h: '&bt_clr 4'}
  - ['', '', '', '', '', '', '&bootloader', '', CAPS, '']
  - [VOL DN, '', '', '', '', '&bootloader', PREV, PP, NEXT, '']
  - ['&studio_unlock', '']
  flash mode:
  - ['', '', '', '', '', '', '', '', '', '']
  - ['', '', '', '', '', '', '', '', '', '']
  - ['', '', '', '', '', '', '', '', '', '']
  - ['', '', '', '', '', '', '', '', '', '']
  - ['', '']
